# This docker-compose file is meant to be used to run appliation and database containers locally
# Not to be used in production environments unless modified with appropriate configs
version: '1'
services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8083:8080"
  #   env_file:
  #     - ./.env
  #   networks:
  #     - learnium
  cache:
    image: redis:latest
    ports:
      - "6372:6379"
  database:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : 123
      POSTGRES_DB : Learnium
    networks:
      - learnium
    volumes:
      - learnium_volume:/var/lib/postgresql/data
networks:
  learnium:
volumes:
  learnium_volume: 
